name: Cache Demo
on: [push]

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Install deps first
      run: npm ci
    - name: prime-cache-9a69e51
      id: cache-step
      uses: actions/cache@v4
      with:
        key: cache-9a69e51
        path: node_modules
    - name: Show cache result
      run: echo "Cache result: ${{ steps.cache-step.outputs.cache-hit }}"
