name: CI with Cache

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache dependencies
        id: cache-9a69e51
        uses: actions/cache@v4
        with:
          path: cache-folder
          key: cache-9a69e51

      - name: prime-cache-9a69e51
        run: echo "Cache hit? -> ${{ steps.cache-9a69e51.outputs.cache-hit }}"

      - name: Create folder
        run: mkdir -p cache-folder
